CREATE TABLE Person (
    Id SERIAL PRIMARY KEY,
    FirstName VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    Email VARCHAR(29) NOT NULL
);

CREATE TABLE "User" (
    Id SERIAL PRIMARY KEY,
    UserName VARCHAR(20) NOT NULL,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DeleteAt TIMESTAMP NULL,
    PersonId INT NOT NULL,
    FOREIGN KEY (PersonId) REFERENCES Person(Id)
);

CREATE TABLE Rol (
    Id SERIAL PRIMARY KEY,
    "Description" VARCHAR(100) NOT NULL,
    "Name" VARCHAR(20) NOT NULL,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DeleteAt TIMESTAMP NULL
);

CREATE TABLE Permission (
    Id SERIAL PRIMARY KEY,
    "Name" VARCHAR(20) NOT NULL,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    Code VARCHAR(50) NOT NULL UNIQUE,
    CreateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DeleteAt TIMESTAMP NULL
);

CREATE TABLE Form (
    Id SERIAL PRIMARY KEY,
    "Name" VARCHAR(20) NOT NULL,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DeleteAt TIMESTAMP NULL
);

CREATE TABLE Module (
    Id SERIAL PRIMARY KEY,
    "Name" VARCHAR(20) NOT NULL,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DeleteAt TIMESTAMP NULL
);

CREATE TABLE RoleUser (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL,
    RolId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES "User"(Id),
    FOREIGN KEY (RolId) REFERENCES Rol(Id)
);

CREATE TABLE RoleFormPermission (
    Id SERIAL PRIMARY KEY,
    RolId INT NOT NULL,
    PermissionId INT NOT NULL,
    FormId INT NOT NULL,
    FOREIGN KEY (RolId) REFERENCES Rol(Id),
    FOREIGN KEY (PermissionId) REFERENCES Permission(Id),
    FOREIGN KEY (FormId) REFERENCES Form(Id)
);

CREATE TABLE FormModule (
    Id SERIAL PRIMARY KEY,
    ModuleId INT NOT NULL,
    FormId INT NOT NULL,
    FOREIGN KEY (ModuleId) REFERENCES Module(Id),
    FOREIGN KEY (FormId) REFERENCES Form(Id)
);
